### ISSUE TITLE
Algorithm for 2018/S4.cpp

### ISSUE THREAD

**Issue by alexapostolu** [sjay05/CCC-Solutions#9]
For the 2018/S4.cpp problem, could I ask what was the algorithm you used, or how did you solve that problem? Sorry if this is off topic, I can't find any answers on that problem though

**Comment by sjay05** [comment]
I don't really remember, but this should help: https://dmoj.ca/problem/ccc18s4/editorial.

**Comment by alexapostolu** [comment]
cool thanks!
